Create User Bmcsdl_1 Identified By 123;
grant create session to BMCSDL_1;
grant create table to BMCSDL_1;
alter user BMCSDL_1 quota 100M on users;

drop user BMCSDL_1 cascade;

GRANT CREATE USER TO BMCSDL_1;          
GRANT CREATE TABLE TO BMCSDL_1;     
GRANT CONNECT TO BMCSDL_1;
GRANT ALTER USER, DROP USER TO BMCSDL_1;  
GRANT CREATE SESSION TO BMCSDL_1;

GRANT ALL PRIVILEGES TO BMCSDL_1;

select * from dba_users;
select * from all_users;

commit

select * from all_users

Select * from nhanvien;
select * from nguoithue;
select * from phong;
select * from dat_phong;

SELECT * FROM USER_ROLE_PRIVS;
SELECT * FROM USER_TAB_PRIVS;
SELECT * FROM USER_SYS_PRIVS; ----------



CREATE TABLE PHONG
(
  MA_PHONG INT PRIMARY KEY,
  TEN_PHONG NVARCHAR2(255),
  TANG INT,
  SO_GIUONG INT,
  GIA FLOAT CHECK (GIA >= 0),
  TRANG_THAI NVARCHAR2(50)
);


CREATE TABLE NHANVIEN
(
  USERNAME NVARCHAR2(255),
  MA_NHANVIEN INT PRIMARY KEY,
  SDT_NV NVARCHAR2(12),
  EMAIL_NV VARCHAR(255),
  PW VARCHAR(255),
  MA_KHACHSAN INT,
  MA_NV_QUANLY INT,
  CONSTRAINT FK_NV_NV FOREIGN KEY (MA_NV_QUANLY) REFERENCES NHANVIEN(MA_NHANVIEN)
);

CREATE TABLE NGUOITHUE
(
  MA_NGUOITHUE INT PRIMARY KEY,
  HOTEN_NT NVARCHAR2(255),
  SDT NVARCHAR2(12),
  EMAIL VARCHAR(255)
);

CREATE TABLE DATPHONG 
(
  MA_DATPHONG INT PRIMARY KEY,
  NGAY_VAO DATE,
  NGAY_RA DATE,
  MA_PHONG INT,
  MA_NGUOITHUE INT,
  MA_NHANVIEN INT,
  CONSTRAINT FK_DP_PH FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG),
  CONSTRAINT FK_DP_NT FOREIGN KEY (MA_NGUOITHUE) REFERENCES NGUOITHUE(MA_NGUOITHUE),
  CONSTRAINT FK_DP_NV FOREIGN KEY (MA_NHANVIEN) REFERENCES NHANVIEN(MA_NHANVIEN)
);

CREATE SEQUENCE nhanvien_seq START WITH 1 INCREMENT BY 1;



INSERT ALL 
INTO PHONG (MA_PHONG, TEN_PHONG, TANG, SO_GIUONG, GIA, TRANG_THAI) VALUES (101, 'Deluxe Room', 1, 2, 500.00, 'Available')
INTO PHONG (MA_PHONG, TEN_PHONG, TANG, SO_GIUONG, GIA, TRANG_THAI) VALUES (102, 'Standard Room', 1, 1, 300.00, 'Occupied')
INTO PHONG (MA_PHONG, TEN_PHONG, TANG, SO_GIUONG, GIA, TRANG_THAI) VALUES (201, 'Suite', 2, 3, 800.00, 'Available')
INTO PHONG (MA_PHONG, TEN_PHONG, TANG, SO_GIUONG, GIA, TRANG_THAI) VALUES (202, 'Family Room', 2, 4, 650.00, 'Under Maintenance')
INTO PHONG (MA_PHONG, TEN_PHONG, TANG, SO_GIUONG, GIA, TRANG_THAI) VALUES (301, 'Luxury Suite', 3, 2, 1000.00, 'Available')
SELECT * FROM DUAL;

INSERT ALL 
INTO NGUOITHUE (MA_NGUOITHUE, HOTEN_NT, SDT, EMAIL) VALUES (1, 'Nguyen Van A', '0934123456', 'nguyenvana@example.com')
INTO NGUOITHUE (MA_NGUOITHUE, HOTEN_NT, SDT, EMAIL) VALUES (2, 'Tran Thi B', '0912345678', 'tranthib@example.com')
INTO NGUOITHUE (MA_NGUOITHUE, HOTEN_NT, SDT, EMAIL) VALUES (3, 'Le Minh C', '0923456789', 'leminhc@example.com')
INTO NGUOITHUE (MA_NGUOITHUE, HOTEN_NT, SDT, EMAIL) VALUES (4, 'Hoang Dung D', '0945123456', 'hoangdungd@example.com')
SELECT * FROM DUAL;



SELECT * FROM PHONG;
SELECT * FROM NHANVIEN;
SELECT * FROM NGUOITHUE;
SELECT * FROM DATPHONG;



CREATE OR REPLACE PROCEDURE ENCRYPT_PW (
    p_plaintext IN VARCHAR2,    
    p_key       IN VARCHAR2,    
    p_ciphertext OUT RAW         
) AS
BEGIN
    p_ciphertext := DBMS_CRYPTO.ENCRYPT(
                        src => UTL_I18N.STRING_TO_RAW(p_plaintext, 'AL32UTF8'),
                        typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
                        key => UTL_I18N.STRING_TO_RAW(p_key, 'AL32UTF8')        
                    );
END;
/
CREATE OR REPLACE PROCEDURE DECRYPT_PW (
    p_ciphertext IN RAW,          
    p_key        IN VARCHAR2,    
    p_plaintext  OUT VARCHAR2     
) AS
    v_decrypted_raw RAW(32767);
BEGIN
    v_decrypted_raw := DBMS_CRYPTO.DECRYPT(
                           src => p_ciphertext,
                           typ => DBMS_CRYPTO.ENCRYPT_AES256 + DBMS_CRYPTO.CHAIN_CBC + DBMS_CRYPTO.PAD_PKCS5,
                           key => UTL_I18N.STRING_TO_RAW(p_key, 'AL32UTF8')
                       );

    p_plaintext := UTL_I18N.RAW_TO_CHAR(v_decrypted_raw, 'AL32UTF8');
END;
/

SELECT USERNAME FROM ALL_USERS
SELECT username FROM users

